[versions]
# libraries
junit = "4.13.2"
junit5 = "5.13.4"
mockito = "5.19.0"
junitPlatform = "1.13.4"
grammarkit = "2022.3.2.2"
intellijStarter = "253.30387.90"
kodein = "7.26.1"

# plugins
kotlin = "2.2.10"
changelog = "2.4.0"
gradleIntelliJPlugin = "2.5.0"
qodana = "2025.2.1"
kover = "0.9.1"
lombok = "8.13.1"
robot = "0.11.23"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
junit5api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit5" }
junit5Params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit5" }
junit5engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit5" }
junitJupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit5" }
junitPlatformLauncher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junitPlatform" }
mockito = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
metricsSquashed = { group = "com.jetbrains.intellij.tools", name = "ide-metrics-collector-starter-squashed", version.ref = "intellijStarter" }
metricsCollector = { group = "com.jetbrains.intellij.tools", name = "ide-metrics-collector", version.ref = "intellijStarter" }
kodein = { group = "org.kodein.di", name = "kodein-di-jvm", version.ref = "kodein"}


[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
gradleIntelliJPlugin = { id = "org.jetbrains.intellij.platform", version.ref = "gradleIntelliJPlugin" }
gradleIntelliJModulePlugin = { id = "org.jetbrains.intellij.platform.modules", version.ref = "gradleIntelliJPlugin" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
lombok = { id = "io.freefair.lombok", version.ref = "lombok" }
grammarkit = { id = "org.jetbrains.grammarkit", version.ref = "grammarkit" }
