[versions]
# libraries
junit = "4.13.2"
junit5 = "6.0.3"
mockito = "5.22.0"
junitPlatform = "6.0.3"
grammarkit = "2023.3.0.2"
intellijStarter = "253.30387.90"

# plugins
changelog = "2.5.0"
gradleIntelliJPlugin = "2.10.5"
qodana = "2025.3.1"
lombok = "9.2.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
junit5api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit5" }
junit5Params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit5" }
junit5engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit5" }
junitJupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit5" }
junitPlatformLauncher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junitPlatform" }
mockito = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
metricsSquashed = { group = "com.jetbrains.intellij.tools", name = "ide-metrics-collector-starter-squashed", version.ref = "intellijStarter" }
metricsCollector = { group = "com.jetbrains.intellij.tools", name = "ide-metrics-collector", version.ref = "intellijStarter" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
gradleIntelliJPlugin = { id = "org.jetbrains.intellij.platform", version.ref = "gradleIntelliJPlugin" }
gradleIntelliJModulePlugin = { id = "org.jetbrains.intellij.platform.modules", version.ref = "gradleIntelliJPlugin" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
lombok = { id = "io.freefair.lombok", version.ref = "lombok" }
grammarkit = { id = "org.jetbrains.grammarkit", version.ref = "grammarkit" }
